export let goplitSource = "data:image/png;base64,iV\n" +
  "BORw0KGgoAAAANSUhEUgAAAB\n" +
  "4AAAAeCAMAAAAM7l6QAAAAAX\n" +
  "NSR0IArs4c6QAAAARnQU1BAA\n" +
  "Cxjwv8YQUAAAIlUExURf////\n" +
  "Ly8tfX1+/v79/f39zc3NXV1d\n" +
  "vb28jIyMXFxc3NzcvLy+Li4q\n" +
  "urq6SkpOnp6bu7u09PTywsLE\n" +
  "VFRTg4OOPj47m5uY+Pj9nZ2d\n" +
  "LS0nR0dB0dHSMjI0FBQRcXF7\n" +
  "e3t5ycnKamps7OzlRUVAUFBS\n" +
  "cnJz8/PxMTE9ra2oKCgnp6eo\n" +
  "6OjgYGBkhISHBwcLy8vODg4N\n" +
  "3d3Z2dnW5ubpqampSUlAsLCw\n" +
  "QEBJWVlWxsbIODg1dXV319fT\n" +
  "s7O7i4uI2NjQAAAA0NDRkZGV\n" +
  "lZWYyMjLq6ulhYWOvr69PT06\n" +
  "WlpUBAQBUVFT09PcPDw3Jyci\n" +
  "0tLTIyMhYWFh4eHgoKChISEk\n" +
  "lJSbGxsXl5eTExMQICAiQkJJ\n" +
  "iYmFxcXGtra+Tk5JGRkWRkZG\n" +
  "pqaiEhITc3NwEBAXFxcampqY\n" +
  "eHh66urnt7exsbGw8PDw4ODk\n" +
  "RERMTExLOzs6GhoaKioigoKB\n" +
  "AQEK+vr6Ojo7W1teXl5b6+vj\n" +
  "k5OZeXl6ysrJubmzMzMzw8PH\n" +
  "Nzc9HR0RERESsrKykpKX9/f5\n" +
  "OTk1VVVTQ0NMLCwqqqqjo6Oi\n" +
  "8vL56enomJiYCAgJmZmczMzI\n" +
  "aGhlBQUIWFhUdHR3h4eNTU1E\n" +
  "tLSxoaGjU1NVpaWmBgYFFRUX\n" +
  "5+fsfHx+Hh4V5eXkpKSkNDQ0\n" +
  "1NTZCQkFJSUmhoaG9vb/b29r\n" +
  "CwsFtbW3x8fB8fHyUlJRgYGH\n" +
  "Z2dgMDAwkJCS4uLgcHBwgICB\n" +
  "QUFKenp5Yh4rcAAAAJcEhZcw\n" +
  "AADsMAAA7DAcdvqGQAAAHYSU\n" +
  "RBVDhPY6AZYGSCMrAAZhZWNi\n" +
  "gTDNg5OLm4oWwGBh5ePn4oEw\n" +
  "IEBIWERUQhbFExcQkICwYkpa\n" +
  "RlZOVYQUxReQVFdrAgAigpq6\n" +
  "iqqWsAWRqaWpIQMWSgrSOtq6\n" +
  "dvYGhkbIJqKwSYmpmrWVhaWd\n" +
  "vY2kFFUIC9ioOjqpOzi6ubnj\n" +
  "tUCAY8uDg8vcx0HBxUvX18xf\n" +
  "2g7kcAT/+AwKBgB3Mnh5AAvV\n" +
  "AlqCgchIULR4RERulEmkfHSM\n" +
  "XGQUWRQHxCYpJcckpqmpGgK1\n" +
  "QIAdLSMxgYMrOyHRwCcnLDoI\n" +
  "JQkJdfUAiiw6WLIh2KS0rdys\n" +
  "rB4lDgaQqmKiojHRwcsk2qfE\n" +
  "rAfCiorgFTvLUqDg6RKTp19c\n" +
  "4NYAEU4OrcKBSc0uSvLicHUY\n" +
  "4K7JubWnJr7Vvbcts7oELIoL\n" +
  "OrO9xFnEGhpzdJE4vhDH2Rei\n" +
  "CqtF+wLn4CWAQFTNSZJA6iJy\n" +
  "skTJk6DSyEAGVV02fMnDV7Dp\n" +
  "DZG9stPHfefIg4BOQvWOiTaq\n" +
  "q8aPESIGdp3WK9ZcuBBqyASD\n" +
  "KsbG+U825KVpWpzF0ltbpJZs\n" +
  "1a6XXrEfpbN6SkREZuMFfZaB\n" +
  "bcGGgGAtmbENE62cx8w+bgjZ\n" +
  "vNzXW2mGWHbA0pzpbbBpXDDR\n" +
  "gYAFiCb3ACxRwkAAAAAElFTk\n" +
  "SuQmCC";

export let eliteGoplitSource = "data:image/png;base64,iV\n" +
  "BORw0KGgoAAAANSUhEUgAAAB\n" +
  "4AAAAeCAMAAAAM7l6QAAAAAX\n" +
  "NSR0IArs4c6QAAAARnQU1BAA\n" +
  "Cxjwv8YQUAAADzUExURf///3\n" +
  "h4eAkJCQAAACsrK6ysrGxsbD\n" +
  "g4OBYWFmlpaU1NTR0dHQMDAy\n" +
  "goKBQUFHd3dwoKCmBgYAsLCz\n" +
  "o6Ojw8PKurqwgICDc3NxkZGT\n" +
  "s7O0lJSY2NjQEBASIiIgICAr\n" +
  "e3twcHBw0NDQ4ODmVlZV1dXT\n" +
  "Q0NC4uLkhISCkpKUVFRQYGBo\n" +
  "yMjAQEBD8/P2FhYSEhIRsbGx\n" +
  "ISEgwMDCwsLIiIiE5OTs/Pz0\n" +
  "pKSlFRUSAgIEFBQREREVlZWX\n" +
  "Jycl9fX9bW1ioqKjExMdLS0n\n" +
  "19fUZGRlBQUHt7e+np6UtLS4\n" +
  "GBgfb29kxMTOzs7GZmZpCQkB\n" +
  "UVFZeXlz5G/1EAAAAJcEhZcw\n" +
  "AADsMAAA7DAcdvqGQAAAEhSU\n" +
  "RBVDhPfZILV4JAEIUnr0YZUW\n" +
  "llJZSlaVL0sIeZlVn2sPf//z\n" +
  "XNLgMUrXzn7MzsveeeAQ70jy\n" +
  "npZnKQwQzymX4BmTYwLZMRKy\n" +
  "s8M1vEXEbcnrdRcCbtx8Iils\n" +
  "DIPUWpvIwVrFbWzD7WN1B1vc\n" +
  "0J+a3a9k69sYtmy+Tvoe3n1W\n" +
  "oL+5ZoCbBRxQF8IMDhkYgxKo\n" +
  "bjE5QInVOciRqhXbTPuZBbb6\n" +
  "Z3o3HBTreibOCyJ3KMy8ZVH9\n" +
  "eA08ndiJhwy4/FDDwyvXSLz5\n" +
  "1dxBB0H4RSwsNI1UfOuXzScf\n" +
  "9JN/2t4NGzo68R3Zewj/FK5L\n" +
  "mpeO9NBvS52Mp713fNWHq4l6\n" +
  "jGJ4kPpTNlrX7o2QA+VQ3+bI\n" +
  "6x1fdkRmY7wvQr/OLrO+xEP9\n" +
  "g7Evsv54YHAAAAAElFTkSuQm\n" +
  "CC";

export let eliteGoplit2Source = "data:image/png;base64,iV\n" +
  "BORw0KGgoAAAANSUhEUgAAAB\n" +
  "4AAAAeCAMAAAAM7l6QAAAAAX\n" +
  "NSR0IArs4c6QAAAARnQU1BAA\n" +
  "Cxjwv8YQUAAAC9UExURdnZ2X\n" +
  "h4eAICAgAAAAcHB3FxcV5eXh\n" +
  "AQEAEBAdbW1vHx8d7e3qGhoQ\n" +
  "sLC3t7ewYGBuHh4c3NzV1dXQ\n" +
  "4ODtvb2wgICAkJCVBQUCQkJC\n" +
  "MjI9ra2vf39zIyMgMDA+bm5m\n" +
  "xsbBgYGN3d3fb29jg4OMvLy/\n" +
  "r6+hYWFkBAQFFRUSwsLO3t7T\n" +
  "8/Py8vL+Dg4OTk5CgoKAwMDM\n" +
  "nJyU5OTgUFBSAgIOzs7FxcXF\n" +
  "NTUw0NDREREScnJzs7O6ysrK\n" +
  "Ojo5OTkxEqnL0AAAAJcEhZcw\n" +
  "AADsMAAA7DAcdvqGQAAAEOSU\n" +
  "RBVDhPrZLpUsJAEITHadRVjK\n" +
  "AmiEFBvKLigRde6Ps/lj3UCO\n" +
  "Sq8odfZbfS3VUzk93I/7GiaK\n" +
  "z6e5m1dSAAropsQMFw02WRJr\n" +
  "AVBRdltlk6arVdlWBTBN1xVc\n" +
  "Li3T22j93IE0QTzk467uTYRw\n" +
  "jdA4tDVZ72Du2zjyzvu7dEf2\n" +
  "ABcGwFhm7OiU/Ac7GTwSlw5u\n" +
  "6Cc2s6i1njws0FGft2ldUvua\n" +
  "7c/CWTa2B0gwQRVNNbt+dkd7\n" +
  "hnXWuv4wc3l5gFQAv6WHGpme\n" +
  "CJM9lszy/u5ZmMmb3W/RDx5E\n" +
  "30PXVVYjjq8Eprf4gPluWTuS\n" +
  "zQSOzGuapzoCfyWTOXTNvWtW\n" +
  "5sJl+21cbNMBX5Vm5/ROQHEf\n" +
  "MNH5xIltAAAAAASUVORK5CYI\n" +
  "I="